#DivideANDConquer Config

ArmySpawnLocationP1XCord:
ArmySpawnLocationP1YCord:
ArmySpawnLocationP1Zord:

ArmySpawnLocationP2XCord:
ArmySpawnLocationP2YCord:
ArmySpawnLocationP2ZCord:

ArmySpawnLocationP3XCord:
ArmySpawnLocationP3YCord:
ArmySpawnLocationP3ZCord:

PlayerTPLocationXCord:
PlayerTPLocationYCord:
PlayerTPLocationZCord:

World: